# This is a basic workflow to help you get started with Actions

name: Code compiler

# Controls when the action will run.
on:
  # Triggers the workflow on push request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "compile"
  compile:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1


      - name: Install arduino platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: compile sketch
        run: arduino-cli compile --fqbn arduino:avr:mega ./code/program
